expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    ports:
      http:
        nodePort: 30002
externalURL: http://__NODE_IP__:30002
harborAdminPassword: "Harbor12345"
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 5Gi
    jobservice:
      jobLog:
        size: 1Gi
    database:
      size: 1Gi
    redis:
      size: 1Gi
trivy:
  enabled: false
notary:
  enabled: false
portal:
  replicas: 1
core:
  replicas: 1
jobservice:
  replicas: 1
registry:
  replicas: 1
